name: Build and Deploy Arcana to All-Inkl

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: ⚡ Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: 📦 Install Dependencies
      run: flutter pub get

    - name: 🏗️ Build Flutter Web
      run: flutter build web --release

    - name: 🔧 Install LFTP
      run: sudo apt-get install -y lftp

    - name: 📂 Sync files to /arcana/ via LFTP
      run: |
        lftp -e "set ftp:ssl-auth TLS; set ftp:ssl-force true; set ssl:verify-certificate no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; mirror -R --verbose --parallel=2 --delete ./build/web /arcana; quit"