name: Build and Deploy React to All-Inkl

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: ⚡ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 📦 Install Dependencies
      run: npm install

    - name: 🏗️ Build Project
      run: npm run build

    - name: 🔧 Install LFTP
      run: sudo apt-get install -y lftp

    - name: 📂 Sync files via LFTP
      run: |
        lftp -e "set ftp:ssl-auth TLS; set ftp:ssl-force true; set ssl:verify-certificate no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; mirror -R --verbose --parallel=2 ./dist /; quit"